//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoList
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Note()
        {
            this.Done = false;
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public bool Done { get; set; }
        public System.DateTime DateAdd { get; set; }
        public Nullable<System.DateTime> DateComplete { get; set; }
        public string Name { get; set; }
    }
}
